[tool.poetry]
name = "testi"
version = "0.1.0"
description = ""
authors = ["Iltsukka <113025832+Iltsukka@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
